---
title: "map assignment"
author: "William Roloff"
date: "2022-10-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(ggplot2)
library(maps)
library(viridisLite)
library(tidyverse)


countries <- read.csv('countries_energy_use.csv')
head(countries)
#countries



countries_land_use <- map_data('world')
head(countries_land_use)
countries_land_use[countries_land_use == "USA"] <- "United States of America"




countries_land_use <- map_data("world") %>%
  mutate(region = str_to_title(region),
         subregion = str_to_title(subregion)) %>%
  left_join(countries, by = c('region' = "Country"))



land_use_map <- ggplot(data = countries_land_use,
            mapping = aes(x = long, y = lat,
                          group = group, 
                          fill = Cropland))
land_use_map <- land_use_map + geom_polygon(color="white")
#land_use_map <- land_use_map + scale_fill_viridis(option="magma", direction=-1)
land_use_map <- land_use_map + guides(fill=guide_legend(title="Cropland Productivity"))
#land_use_map <- land_use_map + coord_map()
land_use_map

```

